#!/usr/bin/env bash
# nix/microvm/run-microvm.sh — host runner for the hardened e2e gate.
# Runs on the Linux KVM host (odin) as root: qemu tap devices, the
# virtiofsd share daemons, and the bridge all need privilege (the
# microvm.nix virtiofsd wrapper refuses non-root, and taps attach to
# a host bridge). One command end to end:
#
#   sudo ./nix/microvm/run-microvm.sh [--state-dir DIR] [--fresh] [--keep]
#
#   --state-dir DIR  host state root (default /var/lib/wyrd-microvm/state)
#   --fresh          wipe $STATE_DIR/run before booting (default: keep,
#                    so a failed run's drives survive for forensics)
#   --keep           leave VMs and network up afterwards for debugging
#
# Flow: build wyrd + three VM runners -> bridge/taps -> ephemeral ssh
# key + e2e-env.sh into the state share -> boot virtiofsd+qemu per VM
# (own cwd each: qemu uses relative socket paths) -> wait for ssh ->
# tests/alpha-microvm.sh -> report -> teardown (unless --keep).
# The whole suite runs under `timeout` (30 min): a hung guest must
# fail the run, never the evening.
set -euo pipefail

STATE_DIR="/var/lib/wyrd-microvm/state"
FRESH=0
KEEP=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --state-dir) STATE_DIR="$2"; shift 2 ;;
    --fresh) FRESH=1; shift ;;
    --keep) KEEP=1; shift ;;
    *) echo "error: unknown flag $1 (see header)" >&2; exit 2 ;;
  esac
done

[[ "$EUID" == 0 ]] || { echo "error: run as root (taps, bridge, virtiofsd need it)" >&2; exit 2; }
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || { echo 'error: run from the wyrd checkout' >&2; exit 2; })"
cd "$ROOT"

BRIDGE="br-wyrd"
NET="10.0.7"
RUN="$STATE_DIR/run"
WORK="$STATE_DIR/work"
SSH_KEY="$STATE_DIR/sshkey"
declare -a DAEMONS=()

die() { echo "  FAIL: $1" >&2; exit 1; }

teardown() {
  for pid in "${DAEMONS[@]}"; do kill "$pid" 2>/dev/null || true; done
  wait 2>/dev/null || true
  if [[ "$KEEP" == 0 ]]; then
    for t in tap-o tap-n tap-r; do ip link del "$t" 2>/dev/null || true; done
    ip link del "$BRIDGE" 2>/dev/null || true
  else
    echo "kept: VMs, taps, and $BRIDGE left up (--keep)"
  fi
}
trap teardown EXIT

echo "==> state dir $STATE_DIR"
mkdir -p "$RUN" "$RUN/logs" "$WORK"
[[ "$FRESH" == 1 ]] && rm -rf "$RUN" && mkdir -p "$RUN" "$RUN/logs"

echo "==> building wyrd + VM runners"
WYRD_OUT="$(nix build "$ROOT#packages.x86_64-linux.wyrd" --no-link --print-out-paths 2>/dev/null | tail -n 1)"
WYRD_BIN="$WYRD_OUT/bin/wyrd"
[[ -x "$WYRD_BIN" ]] || die "host build produced no wyrd binary"
echo "    $WYRD_BIN"
for role in peer-o peer-n relay; do
  nix build "$ROOT#nixosConfigurations.wyrd-$role.config.microvm.runner.qemu" \
    --out-link "$WORK/runner-$role" --print-build-logs 2>&1 | tail -n 2
done

echo "==> network: $BRIDGE ${NET}.0/24"
ip link add "$BRIDGE" type bridge 2>/dev/null || true
ip addr add "$NET.1/24" dev "$BRIDGE" 2>/dev/null || true
ip link set "$BRIDGE" up
declare -A TAP_IP=( [peer-o]=11 [peer-n]=12 [relay]=10 )
declare -A TAP_DEV=( [peer-o]=tap-o [peer-n]=tap-n [relay]=tap-r )

echo "==> ssh key + guest env"
[[ -f "$SSH_KEY" ]] || ssh-keygen -t ed25519 -N "" -f "$SSH_KEY" -q
cp "$SSH_KEY.pub" "$STATE_DIR/ssh_host_key.pub"
{
  echo "# Generated by run-microvm.sh; sourced by the suite in guests."
  printf 'WYRD_BIN=%q\n' "$WYRD_BIN"
  printf 'RELAY_PORT=%q\n' "18761"
  printf 'RELAY_HOST=%q\n' "$NET.10"
  printf 'RELAY_MANAGED=%q\n' "0"
  printf 'CHECKOUT=%q\n' "/etc/wyrd-tests"
  printf 'E2E_ROOT=%q\n' "/mnt/wyrd-state/run"
  printf 'E2E_RUST_LOG=%q\n' "${E2E_RUST_LOG:-}"
} > "$STATE_DIR/e2e-env.sh"

echo "==> booting guests"
: > "$WORK/daemon.pids"
for role in peer-o peer-n relay; do
  tap="${TAP_DEV[$role]}"
  ip link del "$tap" 2>/dev/null || true
  # multi_queue: the microvm runner attaches with queues=<vcpu>
  # (multiqueue); a single-queue tap fails the attach with EINVAL
  # ("could not configure /dev/net/tun") and the guest never boots.
  ip tuntap add dev "$tap" mode tap multi_queue
  ip link set "$tap" up
  ip link set "$tap" master "$BRIDGE"
  vmdir="$WORK/vm-$role"
  mkdir -p "$vmdir"
  ln -sfn "$WORK/runner-$role" "$vmdir/runner"
  ( cd "$vmdir" \
    && ./runner/bin/virtiofsd-run > virtiofsd.log 2>&1 &
    echo $! >> "$WORK/daemon.pids" )
  for i in $(seq 1 30); do
    compgen -G "$vmdir/*.sock" > /dev/null && break
    sleep 1
  done
  compgen -G "$vmdir/*.sock" > /dev/null \
    || { tail -n 5 "$vmdir/virtiofsd.log"; die "$role: virtiofsd socket never appeared"; }
  ( cd "$vmdir" && ./runner/bin/microvm-run > qemu.log 2>&1 &
    echo $! >> "$WORK/daemon.pids" )
  echo "    $role up (tap $tap)"
done
mapfile -t DAEMONS < "$WORK/daemon.pids"

echo "==> waiting for ssh"
SSH="ssh -i $SSH_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -o BatchMode=yes"
for ip in 11 12; do
  for i in $(seq 1 60); do
    $SSH "e2e@$NET.$ip" true 2>/dev/null && break
    [[ "$i" == 60 ]] && die "e2e@$NET.$ip never accepted ssh"
    sleep 2
  done
  echo "    e2e@$NET.$ip reachable"
done

echo "==> running the suite"
set +e
timeout 1800 env \
  "STATE_DIR=$STATE_DIR" \
  "SSH_KEY=$SSH_KEY" \
  "WYRD_BIN=$WYRD_BIN" \
  "RELAY_URL=ws://$NET.10:18761" \
  "PEER_O=e2e@$NET.11" \
  "PEER_N=e2e@$NET.12" \
  bash "$ROOT/tests/alpha-microvm.sh"
STATUS=$?
set -e
[[ "$STATUS" == 0 ]] || die "microvm suite failed (exit $STATUS, logs under $RUN/logs)"
echo "microvm: suite green, logs under $RUN/logs"
