#!/usr/bin/env bash
# lima/run-alpha.sh — host half of the Lima e2e run. All intelligence lives
# in the guest script (tests/alpha-lima.sh); this only moves the binary
# into the guest and starts it.
#
# Usage: ./lima/run-alpha.sh [--keep] [--step N[,N...]]
#   --keep   leave the instance running afterwards for debugging
#   --step   run guest-script steps 1..N (comma lists allowed; the run
#            is the prefix closure, since steps build on each other)
#
# Prerequisites on the host: nix (with the linux-builder for the
# guest-arch binary) and limactl. The guest needs no toolchain.
set -euo pipefail

KEEP=0
ONLY_STEP=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep) KEEP=1; shift ;;
    --step) ONLY_STEP="$2"; shift 2 ;;
    *) echo "error: unknown flag $1" >&2; exit 2 ;;
  esac
done

ROOT="$(git rev-parse --show-toplevel)"
INSTANCE="wyrd-alpha"
SHARE=/tmp/lima
mkdir -p "$SHARE"

# The guest image follows the host architecture (the yaml carries both),
# so the binary must match it: arm64 hosts take the aarch64-linux
# package, Intel hosts the x86_64-linux one.
case "$(uname -m)" in
  arm64|aarch64) LINUX_SYSTEM="aarch64-linux" ;;
  x86_64|amd64) LINUX_SYSTEM="x86_64-linux" ;;
  *) echo "error: unsupported host architecture $(uname -m)" >&2; exit 2 ;;
esac

echo "==> building the $LINUX_SYSTEM wyrd binary on the host"
OUT="$(nix build "$ROOT#packages.$LINUX_SYSTEM.wyrd" --no-link --print-out-paths 2>/dev/null | tail -n 1)"
WYRD_BIN="$OUT/bin/wyrd"
echo "    $WYRD_BIN"

echo "==> exporting the runtime closure for the guest"
readarray -t CLOSURE < <(nix-store -qR "$OUT")
nix-store --export "${CLOSURE[@]}" > "$SHARE/wyrd-closure.nar"
REV="$(python3 -c "import json; print(json.load(open('$ROOT/flake.lock'))['nodes']['nixpkgs']['locked']['rev'])")"
# Shell-quoted, never interpolated raw: a checkout path or a step/log
# filter with shell metacharacters must not become source.
{
  echo "# Generated by lima/run-alpha.sh; sourced by the guest scripts."
  printf 'WYRD_BIN=%q\n' "$WYRD_BIN"
  printf 'NIXPKGS_REV=%q\n' "$REV"
  printf 'RELAY_PORT=%q\n' "18761"
  printf 'E2E_ONLY_STEP=%q\n' "$ONLY_STEP"
  printf 'E2E_RUST_LOG=%q\n' "${E2E_RUST_LOG:-}"
} > "$SHARE/e2e-env.sh"

if ! limactl list 2>/dev/null | grep -q "^$INSTANCE[[:space:]].*Running"; then
  if limactl list 2>/dev/null | grep -q "^$INSTANCE[[:space:]]"; then
    echo "==> starting existing instance $INSTANCE"
    limactl start "$INSTANCE"
  else
    echo "==> creating instance $INSTANCE"
    # The yaml carries a placeholder checkout path; stamp the real one.
    # (limactl --set could do this, but a rendered file is easier to
    # debug.) The replacement is sed-escaped: a checkout path with
    # `&`, `|`, or `\` must land literally.
    ROOT_SED="${ROOT//\\/\\\\}"
    ROOT_SED="${ROOT_SED//|/\\|}"
    ROOT_SED="${ROOT_SED//&/\\&}"
    sed "s|/path/to/wyrd-checkout|$ROOT_SED|" "$ROOT/lima/wyrd-alpha.yaml" \
      > "$SHARE/wyrd-alpha.rendered.yaml"
    limactl start --name="$INSTANCE" "$SHARE/wyrd-alpha.rendered.yaml"
  fi
fi

echo "==> provisioning the guest (idempotent)"
# Run from a host directory that exists in the guest: limactl adopts
# the caller's cwd as the guest workdir, and the caller's checkout
# path is not visible in the guest, so leaving it in place only
# produces "cd: no such file" noise on every shell call.
(cd / && limactl shell "$INSTANCE" -- bash /mnt/wyrd/lima/provision.sh)

echo "==> running the guest contract"
set +e
(cd / && limactl shell "$INSTANCE" -- bash /mnt/wyrd/tests/alpha-lima.sh)
STATUS=$?
set -e

echo "==> logs collected under $SHARE/logs/"
if [[ $KEEP -eq 0 ]]; then
  echo "==> stopping $INSTANCE (--keep to leave it running)"
  limactl stop "$INSTANCE"
fi
exit "$STATUS"
