#!/usr/bin/env bash
# lima/run-alpha.sh — host half of the Lima e2e run. All intelligence lives
# in the guest script (tests/alpha-lima.sh); this only moves the binary
# into the guest and starts it.
#
# Usage: ./lima/run-alpha.sh [--keep] [--step N]
#   --keep   leave the instance running afterwards for debugging
#   --step N run only guest-script step N (passed through as E2E_ONLY_STEP)
#
# Prerequisites on the host: nix (with the linux-builder for the
# aarch64-linux binary) and limactl. The guest needs no toolchain.
set -euo pipefail

KEEP=0
ONLY_STEP=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep) KEEP=1; shift ;;
    --step) ONLY_STEP="$2"; shift 2 ;;
    *) echo "error: unknown flag $1" >&2; exit 2 ;;
  esac
done

ROOT="$(git rev-parse --show-toplevel)"
INSTANCE="wyrd-alpha"
SHARE=/tmp/lima
mkdir -p "$SHARE"

echo "==> building the aarch64-linux wyrd binary on the host"
OUT="$(nix build "$ROOT#packages.aarch64-linux.wyrd" --no-link --print-out-paths 2>/dev/null | tail -n 1)"
WYRD_BIN="$OUT/bin/wyrd"
echo "    $WYRD_BIN"

echo "==> exporting the runtime closure for the guest"
readarray -t CLOSURE < <(nix-store -qR "$OUT")
nix-store --export "${CLOSURE[@]}" > "$SHARE/wyrd-closure.nar"
REV="$(python3 -c "import json; print(json.load(open('$ROOT/flake.lock'))['nodes']['nixpkgs']['locked']['rev'])")"
cat > "$SHARE/e2e-env.sh" <<EOF
# Generated by lima/run-alpha.sh; sourced by the guest scripts.
WYRD_BIN="$WYRD_BIN"
NIXPKGS_REV="$REV"
RELAY_PORT="18761"
E2E_ONLY_STEP="$ONLY_STEP"
E2E_RUST_LOG="${E2E_RUST_LOG:-}"
EOF

if ! limactl list 2>/dev/null | grep -q "^$INSTANCE[[:space:]].*Running"; then
  if limactl list 2>/dev/null | grep -q "^$INSTANCE[[:space:]]"; then
    echo "==> starting existing instance $INSTANCE"
    limactl start "$INSTANCE"
  else
    echo "==> creating instance $INSTANCE"
    # The yaml carries a placeholder checkout path; stamp the real one.
    # (limactl --set could do this, but a rendered file is easier to debug.)
    sed "s|/path/to/wyrd-checkout|$ROOT|" "$ROOT/lima/wyrd-alpha.yaml" > "$SHARE/wyrd-alpha.rendered.yaml"
    limactl start --name="$INSTANCE" "$SHARE/wyrd-alpha.rendered.yaml"
  fi
fi

echo "==> provisioning the guest (idempotent)"
limactl shell "$INSTANCE" -- bash /mnt/wyrd/lima/provision.sh

echo "==> running the guest contract"
set +e
limactl shell "$INSTANCE" -- bash /mnt/wyrd/tests/alpha-lima.sh
STATUS=$?
set -e

echo "==> logs collected under $SHARE/logs/"
if [[ $KEEP -eq 0 ]]; then
  echo "==> stopping $INSTANCE (--keep to leave it running)"
  limactl stop "$INSTANCE"
fi
exit "$STATUS"
